### ISSUE TITLE
Design a website for this repo - comment down to be assigned 

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Portfolio-Collection#16]

**Comment by arhum602** [comment]
I would like to work on this project

**Comment by avinash201199** [comment]
> I would like to work on this project

go ahead :)

**Comment by arhum602** [comment]
@avinash201199 Hopefully no problems. If you need any more functionalities to be added do let me know.

**Comment by avinash201199** [comment]
![image](https://user-images.githubusercontent.com/61057666/193453137-30ae89cf-c6e7-4828-81a7-512d610bad0d.png)

you can add the details of the portfolios instead of this

**Comment by arhum602** [comment]
> guide the new contributors to add their details in the code
@avinash201199 i will update the readme file and add instructions

Also wdym by details of the portfolio's??

**Comment by avinash201199** [comment]
> > guide the new contributors to add their details in the code
> > @avinash201199 i will update the readme file and add instructions
> 
> Also wdym by details of the portfolio's??

means it should show the list of people who have uploaded the portfolio in this repo

**Comment by gulshanjakhon** [comment]
Hi @avinash201199 , please check my PR Gulshan's Portfolio added #201 
Thank you
