### ISSUE TITLE
I want to add my portfolio

### ISSUE THREAD

**Issue by anamikarawat** [avinash201199/Portfolio-Collection#17]
I want to contribute to this repo . please assign me this issue under hacktoberfest 2022.

**Comment by anamikarawat** [comment]
I have added my portfolio and you have added it too in your repo !

**Comment by avinash201199** [comment]
> I have added my portfolio and you have added it too in your repo !

what type of file you have added ? it's unclickable and nothing to show

**Comment by anamikarawat** [comment]
> > I have added my portfolio and you have added it too in your repo !
> 
> what type of file you have added ? it's unclickable and nothing to show

I have added a folder name as Anamika Rawat
