### ISSUE TITLE
Create a simple website for this repo to list all the portfolio source code with required features ( using html , css , js)

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Portfolio-Collection#246]
If you are interested to work on this repo , comment on this issue , will assign you !

**Comment by ritik7102** [comment]
het @avinash201199 yes im intrested

**Comment by avinash201199** [comment]
> het @avinash201199 yes im intrested

great , you can start working , let me know if you need any help

**Comment by ritik7102** [comment]
hey @avinash201199  actully im new to all this thing but i have strong fundamentals of html and css so can u elaborate more about the work please

**Comment by avinash201199** [comment]
> hey @avinash201199 actully im new to all this thing but i have strong fundamentals of html and css so can u elaborate more about the work please

you can design a basic website containing list of portfolio , about section , contact us , you can show portfolio list in a form of cards , name and its link , once the basic structure is created , we can think further , its on you how to design !

**Comment by ritik7102** [comment]
got it

**Comment by dhruvabhat24** [comment]
@avinash201199  I have noticed that it is assigned to someone already . But If I can work on it assign it to me.

**Comment by avinash201199** [comment]
> @avinash201199 I have noticed that it is assigned to someone already . But If I can work on it assign it to me.

you can work on it , whoever first make it , I will accept the pr after reviewing it and the other person can contribute by adding new features or improving it! I have posted a reel on this repo and it's gone viral (450k) views till now so it's a very good project

**Comment by dhruvabhat24** [comment]
> > @avinash201199 I have noticed that it is assigned to someone already . But If I can work on it assign it to me.
> 
> you can work on it , whoever first make it , I will accept the pr after reviewing it and the other person can contribute by adding new features or improving it! I have posted a reel on this repo and it's gone viral (450k) views till now so it's a very good project

Thankyou.. I got to know about this from that reel . I will work on it as soon as possible

**Comment by avinash201199** [comment]
> > > @avinash201199 I have noticed that it is assigned to someone already . But If I can work on it assign it to me.
> > 
> > 
> > you can work on it , whoever first make it , I will accept the pr after reviewing it and the other person can contribute by adding new features or improving it! I have posted a reel on this repo and it's gone viral (450k) views till now so it's a very good project
> 
> Thankyou.. I got to know about this from that reel . I will work on it as soon as possible

All the best !

**Comment by dhruvabhat24** [comment]
@avinash201199 do you need just a list of templates or a card displaying the image of the site with buttons having links to source code 
I also request you to open the discussion session for this repo so that we can clear our queries in feture

**Comment by avinash201199** [comment]
> @avinash201199 do you need just a list of templates or a card displaying the image of the site with buttons having links to source code I also request you to open the discussion session for this repo so that we can clear our queries in feture

a card displaying the image of the site with buttons having links to the source code will be awesome. Opened discussion sesion !

**Comment by dhruvabhat24** [comment]
I have raised the pull request #259 
This pull request also conatins my protfolio design 
I hope it meets your requirements 
If any changes required in the webpage you can tell me

**Comment by dhruvabhat24** [comment]
> > @avinash201199 do you need just a list of templates or a card displaying the image of the site with buttons having links to source code I also request you to open the discussion session for this repo so that we can clear our queries in feture
> 
> a card displaying the image of the site with buttons having links to the source code will be awesome. Opened discussion sesion !

I have raised the pull request #259 
This pull request also conatins my protfolio design 
I hope it meets your requirements 
If any changes required in the webpage you can tell me
