### ISSUE TITLE
Improve Readme.md file 

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Portfolio-Collection#257]
Please comment on this issue , I will assign to you !

**Comment by dhruvabhat24** [comment]
I will work on this

**Comment by 1-14R51-14** [comment]
Ill do this

**Comment by lmfaolmaolol** [comment]
> Please comment on this issue , I will assign to you !




I would lkie to work on this

**Comment by Harshh18** [comment]
If this is still open, I would like to work on this, will complete it within a week.
